sudo: required
services:
- docker
env:
  -NODE_VERSION=8-jessie
  -NODE_VERSION=10-jessie
script:
- bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
- docker build -t node:$NODE_VERSION  --build-arg NODE_IMAGE="node.$NODE_VERSION" .
- docker images
- docker tag node:$NODE_VERSION $DOCKER_LOGIN/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
- docker push $DOCKER_LOGIN/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
